### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 376 but got size 375 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by HereNowL** [walking-shadow/Official_Remote_Sensing_Mamba#12]
Traceback (most recent call last):
  File "/data3/limeixuan/Official_RSMamba/semantic_segmentation_mamba/inference.py", line 83, in <module>
    train_net(dataset_name='img_example/Road')
  File "/data3/limeixuan/Official_RSMamba/semantic_segmentation_mamba/inference.py", line 62, in train_net
    ss_preds = net(batch_img1)
  File "/home/limeixuan/anaconda3/envs/vmb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data3/limeixuan/Official_RSMamba/semantic_segmentation_mamba/rs_mamba_ss.py", line 1245, in forward
    decode_1 = self.deocder_block1(decode_2, x1_1)
  File "/home/limeixuan/anaconda3/envs/vmb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data3/limeixuan/Official_RSMamba/semantic_segmentation_mamba/rs_mamba_ss.py", line 1014, in forward
    output = torch.cat([de, en], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 376 but got size 375 for tensor number 1 in the list.
请问作者这是什么原因？另外想问一下作者在训练时有使用VMamba给出的预训练参数吗

**Comment by walking-shadow** [comment]
我觉得是你的输入图片大小不是32的倍数，这导致了这个问题。因为我的网络进行了32倍的下采样再上采样，这会使得你的图片下采样再上采样之后无法恢复到原来的大小，存在比较细小的误差。
另外，因为我们是为了验证SSM-based模型在遥感密集预测任务中的潜力，因此我们没有使用VMamba给出的预训练参数

**Comment by HereNowL** [comment]
我是直接使用[Massachusetts Roads Dataset](https://www.cs.toronto.edu/~vmnih/data/)中的几张样例图片进行测试的，需要做哪些额外的调整吗？
另外，不使用预训练参数也可以获得论文中提到的很好的结果是吗？
感谢解答。

**Comment by walking-shadow** [comment]
[Massachusetts Roads Dataset](https://www.cs.toronto.edu/~vmnih/data/)里的图片，我都把它们裁剪成了1024×1024大小。另外，不使用预训练参数也可以获得很好的结果，由于我们的RSM结构非常简单，你也可以自由的对它们进行更改
