### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by xbd1519722757** [walking-shadow/Official_Remote_Sensing_Mamba#3]
Hi, I have encountered an error reported as below:
```
Traceback (most recent call last):
  File "D:\Official_Remote_Sensing_Mamba-main\semantic_segmentation_mamba\train.py", line 196, in <module>
    auto_experiment()
  File "D:\Official_Remote_Sensing_Mamba-main\semantic_segmentation_mamba\train.py", line 41, in auto_experiment
    train_net(dataset_name=ph.dataset_name)
  File "D:\Official_Remote_Sensing_Mamba-main\semantic_segmentation_mamba\train.py", line 112, in train_net
    net = RSM_SS(dims=ph.dims, depths=ph.depths, ssm_d_state=ph.ssm_d_state, ssm_dt_rank=ph.ssm_dt_rank, \
  File "D:\Official_Remote_Sensing_Mamba-main\semantic_segmentation_mamba\rs_mamba_ss.py", line 1112, in __init__
    self.encoder_layers.append(self._make_layer(
  File "D:\Official_Remote_Sensing_Mamba-main\semantic_segmentation_mamba\rs_mamba_ss.py", line 1239, in _make_layer
    blocks.append(OSSBlock(
  File "D:\Official_Remote_Sensing_Mamba-main\semantic_segmentation_mamba\rs_mamba_ss.py", line 949, in __init__
    self.op = _OSSM(
  File "D:\Official_Remote_Sensing_Mamba-main\semantic_segmentation_mamba\rs_mamba_ss.py", line 687, in __init__
    self.in_proj = nn.Linear(d_model, d_proj, bias=bias, **factory_kwargs)
TypeError: __init__() got an unexpected keyword argument 'device'
```
I have tried a few things but could not solve the problem. Can you tell me how to solve this problem? :-)

**Comment by walking-shadow** [comment]
This issue may arise due to an incorrect or corrupted version of your torch library. You can try reinstalling torch and its dependencies, or create a new Python environment and reinstall them. Then, run the following code to verify if the torch library is functioning properly:

```
import torch.nn as nn
a = nn.Linear(100, 50, bias=True, device=None, dtype=None)
```

**Comment by xbd1519722757** [comment]
Thanks!
