### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1536 but got size 384 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by Weishangbin** [walking-shadow/Official_Remote_Sensing_Mamba#4]
作者您好，我在WHU数据集上运行分割代码时出现了报错
Traceback (most recent call last):
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 194, in <module>
    auto_experiment()
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 40, in auto_experiment
    train_net(dataset_name=ph.dataset_name)
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 161, in train_net
    train_val_test(
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/utils/utils.py", line 148, in train_val_test
    preds = net(image)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/rs_mamba_ss.py", line 1279, in forward
    decode_3 = self.deocder_block3(x1_4, x1_3)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/rs_mamba_ss.py", line 1014, in forward
    output = torch.cat([de, en], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1536 but got size 384 for tensor number 1 in the list.
请问您知道是什么原因吗，我除了路径外没有对您的代码做任何更改

**Comment by walking-shadow** [comment]
这是tensor形状导致的问题，你可以在rs_mamba_ss.py中的1277行下面加入以下代码，把tensor的形状转换过来即可，相应代码我也在仓库更新了
```
        x1_1 = rearrange(x1_1, "b h w c -> b c h w").contiguous()
        x1_2 = rearrange(x1_2, "b h w c -> b c h w").contiguous()
        x1_3 = rearrange(x1_3, "b h w c -> b c h w").contiguous()
        x1_4 = rearrange(x1_4, "b h w c -> b c h w").contiguous()
```

**Comment by Weishangbin** [comment]
好的非常感谢您的回答，跑通了谢谢

**Comment by Weishangbin** [comment]
Start Train!
epoch 0 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:34<00:00,  3.41it/s]
train f1score: 0.7664371132850647
train epoch loss: 0.5266982316970825
Start Train!
epoch 1 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:30<00:00,  3.43it/s]
train f1score: 0.8809574246406555
train epoch loss: 0.29145026206970215
Start Train!
epoch 2 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:42<00:00,  3.37it/s]
train f1score: 0.8980151414871216
train epoch loss: 0.2502601444721222
Start Train!
epoch 3 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:38<00:00,  3.39it/s]
train f1score: 0.9061115384101868
train epoch loss: 0.22851459681987762
Start Train!
epoch 4 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:23<00:00,  3.46it/s]
train f1score: 0.6482999324798584
train epoch loss: nan
Start Train!
epoch 5 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:11<00:00,  3.53it/s]
train f1score: 0.0
train epoch loss: nan
Start Train!
epoch 6 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:21<00:00,  3.48it/s]
train f1score: 0.0
train epoch loss: nan
Start Train!
epoch 7 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:08<00:00,  3.54it/s]
train f1score: 0.0
train epoch loss: nan
Start Train!
epoch 8 info 4734 - 4736: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [11:04<00:00,  3.56it/s]
train f1score: 0.0
train epoch loss: nan
Start Train!
epoch 9 info 2662 - 2664:  56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                             | 1331/2368 [06:12<04:50,  3.57it/s]
Traceback (most recent call last):
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 194, in <module>
    auto_experiment()
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 40, in auto_experiment
    train_net(dataset_name=ph.dataset_name)
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 161, in train_net
    train_val_test(
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/utils/utils.py", line 179, in train_val_test
    batch_metrics = metric_collection.forward(preds.float(), labels.int().unsqueeze(1))  # compute metric
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/collections.py", line 157, in forward
    res = {k: m(*args, **m._filter_kwargs(**kwargs)) for k, m in self.items(keep_base=True, copy_state=False)}
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/collections.py", line 157, in <dictcomp>
    res = {k: m(*args, **m._filter_kwargs(**kwargs)) for k, m in self.items(keep_base=True, copy_state=False)}
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 391, in wrapped_func
    update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/classification/accuracy.py", line 219, in update
    mode = _mode(preds, target, self.threshold, self.top_k, self.num_classes, self.multiclass, self.ignore_index)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/functional/classification/accuracy.py", line 59, in _mode
    mode = _check_classification_inputs(
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 271, in _check_classification_inputs
    case, implied_classes = _check_shape_and_type_consistency(preds, target)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 86, in _check_shape_and_type_consistency
    raise ValueError(
ValueError: If `preds` and `target` are of shape (N, ...) and `preds` are floats, `target` should be binary.
Traceback (most recent call last):
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 194, in <module>
    auto_experiment()
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 40, in auto_experiment
    train_net(dataset_name=ph.dataset_name)
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 161, in train_net
    train_val_test(
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/utils/utils.py", line 179, in train_val_test
    batch_metrics = metric_collection.forward(preds.float(), labels.int().unsqueeze(1))  # compute metric
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/collections.py", line 157, in forward
    res = {k: m(*args, **m._filter_kwargs(**kwargs)) for k, m in self.items(keep_base=True, copy_state=False)}
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/collections.py", line 157, in <dictcomp>
    res = {k: m(*args, **m._filter_kwargs(**kwargs)) for k, m in self.items(keep_base=True, copy_state=False)}
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 391, in wrapped_func
    update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/classification/accuracy.py", line 219, in update
    mode = _mode(preds, target, self.threshold, self.top_k, self.num_classes, self.multiclass, self.ignore_index)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/functional/classification/accuracy.py", line 59, in _mode
    mode = _check_classification_inputs(
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 271, in _check_classification_inputs
    case, implied_classes = _check_shape_and_type_consistency(preds, target)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 86, in _check_shape_and_type_consistency
    raise ValueError(
ValueError: If `preds` and `target` are of shape (N, ...) and `preds` are floats, `target` should be binary.
又尝试一次后出现了这个错误

**Comment by walking-shadow** [comment]
出现nan可能是因为数据问题，或者是设置得半精度的问题，你可以把amp取消一下，用全精度进行训练。
出现的错误看起来很奇怪，因为它是在一个epoch的某个step出现的，并且前面8个epoch都是可以计算出指标的，这说明计算指标的代码没有问题，可能是因为一直出现nan使得模型的输出也变成了nan，也可能是其他原因。你可以先用全精度训练看看有没有问题，如果还有问题的话，可以检查一下数据

**Comment by Weishangbin** [comment]
epoch 138 info 4734 - 4736: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [10:41<00:00,  3.69it/s]
train f1score: 0.9609348177909851
train epoch loss: 0.09737631678581238
Start Train!
epoch 139 info 4734 - 4736: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2368/2368 [10:39<00:00,  3.70it/s]
train f1score: 0.960427463054657
train epoch loss: 0.10030605643987656
Start Validation!
epoch 139 info 26 - 28:   5%|████████████▊                                                                                                                                                                                                                                                  | 13/259 [00:02<00:48,  5.11it/s]
Traceback (most recent call last):
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 195, in <module>
    auto_experiment()
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 40, in auto_experiment
    train_net(dataset_name=ph.dataset_name)
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/train.py", line 178, in train_net
    train_val_test(
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/utils/utils.py", line 179, in train_val_test
    batch_metrics = metric_collection.forward(preds.float(), labels.int().unsqueeze(1))  # compute metric
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/collections.py", line 157, in forward
    res = {k: m(*args, **m._filter_kwargs(**kwargs)) for k, m in self.items(keep_base=True, copy_state=False)}
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/collections.py", line 157, in <dictcomp>
    res = {k: m(*args, **m._filter_kwargs(**kwargs)) for k, m in self.items(keep_base=True, copy_state=False)}
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 391, in wrapped_func
    update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/classification/accuracy.py", line 219, in update
    mode = _mode(preds, target, self.threshold, self.top_k, self.num_classes, self.multiclass, self.ignore_index)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/functional/classification/accuracy.py", line 59, in _mode
    mode = _check_classification_inputs(
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 271, in _check_classification_inputs
    case, implied_classes = _check_shape_and_type_consistency(preds, target)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 86, in _check_shape_and_type_consistency
    raise ValueError(
ValueError: If `preds` and `target` are of shape (N, ...) and `preds` are floats, `target` should be binary.
您好我在训练137轮时出现了同样的错误，上面的指标也正常，突然出现了这个错误，我在尝试使用训练好的pth文件进行测试时也发生了
Traceback (most recent call last):
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/inference.py", line 80, in <module>
    train_net(dataset_name='your_dataset_name')
  File "/home/lsj729/project/Official_Remote_Sensing_Mamba-main/semantic_segmentation_mamba/inference.py", line 65, in train_net
    metric_collection.update(ss_preds, labels)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/collections.py", line 183, in update
    m.update(*args, **m_kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/metric.py", line 391, in wrapped_func
    update(*args, **kwargs)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/classification/accuracy.py", line 219, in update
    mode = _mode(preds, target, self.threshold, self.top_k, self.num_classes, self.multiclass, self.ignore_index)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/functional/classification/accuracy.py", line 59, in _mode
    mode = _check_classification_inputs(
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 268, in _check_classification_inputs
    _basic_input_validation(preds, target, threshold, multiclass, ignore_index)
  File "/home/lsj729/anaconda3/envs/vmamba/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 59, in _basic_input_validation
    raise ValueError("The `preds` and `target` should have the same first dimension.")
ValueError: The `preds` and `target` should have the same first dimension.您知道可能是哪里出现了问题吗

**Comment by walking-shadow** [comment]
按理来说你前面跑这么多epoch都算出指标来了，再接着算指标不应该出问题，你可以把问题拉给GPT问一问。rs_mamba_ss.py里num_classes默认设置为1000，但是我是没有用到这个参数的，它是原来的VMamba进行分类的参数，分割这边用不到的

**Comment by blacksheeplzu** [comment]
![1713431577248](https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/102464114/0c24e263-95c6-4657-8b20-3499769e8cf9)
您好，我在跑CD任务时也出现了这个问题，全都变为0/nan

**Comment by walking-shadow** [comment]
出现nan可能是因为数据问题，或者是设置得半精度的问题，你可以把amp取消一下，用全精度进行训练。

> ![1713431577248](https://private-user-images.githubusercontent.com/102464114/323541228-0c24e263-95c6-4657-8b20-3499769e8cf9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzY5NDYsIm5iZiI6MTcxMzQzNjY0NiwicGF0aCI6Ii8xMDI0NjQxMTQvMzIzNTQxMjI4LTBjMjRlMjYzLTk1YzYtNDY1Ny04YjIwLTM0OTk3NjllOGNmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMDM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWUyNTkyZGNiYmJjZTQ3ZGY5OTcyMzFjNjkwYTc0NTNmYmNiNWM2YmI4YWI2ZmI1MzU2MzFhZWU1MDE2ZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gWMN17xPvm7HZolxLtpuHuaq1lnowRoW9ZNAb4MUr6Y) 您好，我在跑CD任务时也出现了这个问题，全都变为0/nan

**Comment by blacksheeplzu** [comment]
> 出现nan可能是因为数据问题，或者是设置得半精度的问题，你可以把amp取消一下，用全精度进行训练。
> 
> > ![1713431577248](https://private-user-images.githubusercontent.com/102464114/323541228-0c24e263-95c6-4657-8b20-3499769e8cf9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzY5NDYsIm5iZiI6MTcxMzQzNjY0NiwicGF0aCI6Ii8xMDI0NjQxMTQvMzIzNTQxMjI4LTBjMjRlMjYzLTk1YzYtNDY1Ny04YjIwLTM0OTk3NjllOGNmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMDM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWUyNTkyZGNiYmJjZTQ3ZGY5OTcyMzFjNjkwYTc0NTNmYmNiNWM2YmI4YWI2ZmI1MzU2MzFhZWU1MDE2ZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gWMN17xPvm7HZolxLtpuHuaq1lnowRoW9ZNAb4MUr6Y) 您好，我在跑CD任务时也出现了这个问题，全都变为0/nan

这是参考了您上面的回答已经使用全精度训练，现在跑完之后发现后面指标突然又会出现，但这个自建数据集在其他模型上能跑70-75，但在这里只有30-40f1 我再去看一看感谢你的回答

**Comment by LPeng625** [comment]
> > 出现nan可能是因为数据问题，或者是设置得半精度的问题，你可以把amp取消一下，用全精度进行训练。
> > > ![1713431577248](https://private-user-images.githubusercontent.com/102464114/323541228-0c24e263-95c6-4657-8b20-3499769e8cf9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzY5NDYsIm5iZiI6MTcxMzQzNjY0NiwicGF0aCI6Ii8xMDI0NjQxMTQvMzIzNTQxMjI4LTBjMjRlMjYzLTk1YzYtNDY1Ny04YjIwLTM0OTk3NjllOGNmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMDM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWUyNTkyZGNiYmJjZTQ3ZGY5OTcyMzFjNjkwYTc0NTNmYmNiNWM2YmI4YWI2ZmI1MzU2MzFhZWU1MDE2ZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gWMN17xPvm7HZolxLtpuHuaq1lnowRoW9ZNAb4MUr6Y) 您好，我在跑CD任务时也出现了这个问题，全都变为0/nan
> 
> 这是参考了您上面的回答已经使用全精度训练，现在跑完之后发现后面指标突然又会出现，但这个自建数据集在其他模型上能跑70-75，但在这里只有30-40f1 我再去看一看感谢你的回答

您好，我跑道路数据集也出现这个问题了，大概在26个epoch后，请问您解决了吗？

**Comment by LPeng625** [comment]
> 出现nan可能是因为数据问题，或者是设置得半精度的问题，你可以把amp取消一下，用全精度进行训练。
> 
> > ![1713431577248](https://private-user-images.githubusercontent.com/102464114/323541228-0c24e263-95c6-4657-8b20-3499769e8cf9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzY5NDYsIm5iZiI6MTcxMzQzNjY0NiwicGF0aCI6Ii8xMDI0NjQxMTQvMzIzNTQxMjI4LTBjMjRlMjYzLTk1YzYtNDY1Ny04YjIwLTM0OTk3NjllOGNmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMDM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWUyNTkyZGNiYmJjZTQ3ZGY5OTcyMzFjNjkwYTc0NTNmYmNiNWM2YmI4YWI2ZmI1MzU2MzFhZWU1MDE2ZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gWMN17xPvm7HZolxLtpuHuaq1lnowRoW9ZNAb4MUr6Y) 您好，我在跑CD任务时也出现了这个问题，全都变为0/nan

我把半精度取消也会出现这种问题，请问有解决办法吗

**Comment by LPeng625** [comment]
<img width="628" alt="image" src="https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/25023673/d510ca5c-4b2e-4657-ae7c-7c4e3c77ada0">
这个参数貌似没有在模型中起作用
<img width="731" alt="image" src="https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/25023673/634065e0-e190-43a2-9cea-9b298378904d">
应该是在这个地方改吧
